menu: #TITLE: link
  About: about/
  Archives: archives/
  Links: links/

profile_link: about/
avatar: /images/profile.png

instantclick: true

service_worker: false

gitment:
 username: 
 repo: 
 id: 
 secret: 

disqus_shortname: 

twitter: caisiduo

hitokoto: false